kind: pipeline
type: ssh
name: default

server:
  host: 106.75.237.248
  user: root
  password:
    from_secret: SSH_PWD

steps:
- name: deploy
  environment:
      PWD_A:
        from_secret: PWD_A
  commands:
  - echo $PWD_A
  - docker-compose up -d --force-recreate
  - docker ps